### ISSUE TITLE
AppSetup is not triggered during installation

### ISSUE THREAD

**Issue by peters** [Squirrel/OldSquirrelForWindows#127]
Tested with 0.6.20 AppSetup derived class is not invoked during installation. The file is present in the main assembly.

``` cs
public class ShimmerConfig : AppSetup
    {

        private static readonly Assembly Assembly = Assembly.GetExecutingAssembly();

        private static readonly string ProductName = Assembly.GetAttribute<AssemblyProductAttribute>().Product;

        public override string ShortcutName
        {
            get
            {
                return ProductName;
            }
        }

        public override void OnAppInstall()
        {
            // add application to windows boot
            Registry.CurrentUser.OpenSubKey("SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run", true)
                .SetValue(ProductName, Assembly.Location);
        }

        public override void OnAppUninstall()
        {
            // remove application from windows boot
            Registry.CurrentUser.OpenSubKey("SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Run", true)
                .DeleteSubKey(ProductName);
        }

    }
```

**Comment by shiftkey** [comment]
Can you share the %APPDATA%/Shimmer/**YourApp**.txt file? 

This might shed some light on what's currently occurring...

**Comment by peters** [comment]
@shiftkey https://gist.github.com/peters/6508238

**Comment by shiftkey** [comment]
```
WARN | 2013-09-10 12:18:34  +02 | InstallerHookOperations: Couldn't load types from module: 
    System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. 
    Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Shimmer.Client.InstallerHookOperations.<findAppSetupsToRun>b__13(Module x)
WARN | 2013-09-10 12:18:34  +02 | InstallerHookOperations: Could not find any AppSetup instances
```

Right, so let me push some tracing on those `LoaderException` issues in the next release and I'll get you to re-test.

**Comment by shiftkey** [comment]
See #128 for that change

**Comment by peters** [comment]
@shiftkey It would be awesome if you could give us a access to the current log object for adding our own messages.

**Comment by shiftkey** [comment]
What sorts of messages do you want to capture? If you want to see specific events from Shimmer inside the log, they should already be there...

**Comment by allenpetersen** [comment]
I don't know if this is related or not. My AppSetup stopped working when I added a second AppSetup instance for another .EXE file we have in our install folder. This is a support app used to invoke some 3rd party code in its own address space. I only want a shortcut for the main app so I implemented a AppSetup for both .EXEs with an empty list for GetAppShortcutList for the support app. When I make an installer I don't get any shortcuts and the main app doesn't run after setup is done.

```
...
WARN | 2013-09-10 10:34:10 AM -07 | InstallerHookOperations: Couldn't load types from module: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
     at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
     at System.Reflection.RuntimeModule.GetTypes()
     at Shimmer.Client.InstallerHookOperations.<findAppSetupsToRun>b__13(Module x)
WARN | 2013-09-10 10:34:10 AM -07 | InstallerHookOperations: Could not find any AppSetup instances
INFO | 2013-09-10 10:34:10 AM -07 | InstallerHookOperations: We have an exe: C:\Users\USER\AppData\Local\App\app-9.42.0.1\MainApp.exe
INFO | 2013-09-10 10:34:10 AM -07 | InstallerHookOperations: We have an exe: C:\Users\USER\AppData\Local\App\app-9.42.0.1\SupperApp.exe
...
```

**Comment by shiftkey** [comment]
@allenpetersen 

> I only want a shortcut for the main app so I implemented a AppSetup for both .EXEs with an empty list for GetAppShortcutList for the support app. 

Makes sense

> When I make an installer I don't get any shortcuts and the main app doesn't run after setup is done.

That, however, does not.

If you can update to `0.6.21` and generate a new installer, it should log out the LoaderExceptions (and specify which module is failing) to help us isolate what's occurring here.

**Comment by allenpetersen** [comment]
It looks like it is trying to load the files from the temp directory not the newly install app directory. I didn't get a chance to debug the installer process tonight.

```
WARN | 2013-09-10 08:44:10 PM -07 | InstallerHookOperations: Couldn't load types from module C:\Users\allen.petersen\AppData\Local\ProclaimApp\app-9.42.0.1\Proclaim.exe: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Shimmer.Client.InstallerHookOperations.<findAppSetupsToRun>b__13(Module x)
WARN | 2013-09-10 08:44:10 PM -07 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'Libronix.Utility.Windows.Controls, Version=9.42.0.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'Libronix.Utility.Windows.Controls, Version=9.42.0.1, Culture=neutral, PublicKeyToken=null'

=== Pre-bind state information ===
LOG: User = LRSCORP\allen.petersen
LOG: DisplayName = Libronix.Utility.Windows.Controls, Version=9.42.0.1, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///C:/Users/allen.petersen/AppData/Local/Temp/{11de21d0-7da0-475e-8393-c55577235a9c}/.ba1/
LOG: Initial PrivatePath = NULL
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\allen.petersen\AppData\Local\Temp\{11de21d0-7da0-475e-8393-c55577235a9c}\.ba1\BootstrapperCore.config
LOG: Using host configuration file: C:\Users\ALLEN~1.PET\AppData\Local\Temp\{11de21d0-7da0-475e-8393-c55577235a9c}\.ba1\BootstrapperCore.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/Users/allen.petersen/AppData/Local/Temp/{11de21d0-7da0-475e-8393-c55577235a9c}/.ba1/Libronix.Utility.Windows.Controls.DLL.
LOG: Attempting download of new URL file:///C:/Users/allen.petersen/AppData/Local/Temp/{11de21d0-7da0-475e-8393-c55577235a9c}/.ba1/Libronix.Utility.Windows.Controls/Libronix.Utility.Windows.Controls.DLL.
LOG: Attempting download of new URL file:///C:/Users/allen.petersen/AppData/Local/Temp/{11de21d0-7da0-475e-8393-c55577235a9c}/.ba1/Libronix.Utility.Windows.Controls.EXE.
LOG: Attempting download of new URL file:///C:/Users/allen.petersen/AppData/Local/Temp/{11de21d0-7da0-475e-8393-c55577235a9c}/.ba1/Libronix.Utility.Windows.Controls/Libronix.Utility.Windows.Controls.EXE.
```

**Comment by shiftkey** [comment]
@allenpetersen that's fine. I think we can hijack the [AppDomain.Resolve](http://msdn.microsoft.com/en-us/library/system.appdomain.assemblyresolve.aspx) method to use the installed app directory as a fallback, if necessary.

**Comment by peters** [comment]
@shiftkey Could you add an OnBeforeAppInstall method? A simple use case would be to kill a conflicting program.

**Comment by anaisbetts** [comment]
> @allenpetersen that's fine. I think we can hijack the AppDomain.Resolve method to use the installed app directory as a fallback, if necessary.

It might be a better idea long-term to have people make a separate DLL for `IAppSetup`s. While having it in the EXE is super convenient, we're gonna keep hitting these "Can't load the entire app's DLLs in our AppDomain" bugs.

**Comment by shiftkey** [comment]
@paulcbetts that's kinda what I had in mind. Make it so.

**Comment by shiftkey** [comment]
@peters 

> Could you add an OnBeforeAppInstall method? A simple use case would be to kill a conflicting program.

Why would you need to kill the program at this point? We're deploying the new version to a different folder, and files for the current version should be marked as "delete on next boot"

**Comment by peters** [comment]
@shiftkey Say a thirdparty application has put a lock on some files you need access to (not ACL'ed), then i need to kill that program (it's not the application we are updating) before the installation can continue because i will try to make modifications to these locked files in OnAppInstall

**Comment by peters** [comment]
Sure, i could kill the program in OnAppInstall but i'd love more seperation of the logic so i don't end up with a unbearable amount of code in OnAppInstall. :dancers:

**Comment by shiftkey** [comment]
> Say a thirdparty application has put a lock on some files you need access to (not ACL'ed), 

But are these files part of the install? 
- If so, they'll be deployed to a different folder before setup
- If not, you could have a number of IAppSetup tasks which run to keep things composable

> then i need to kill that program (it's not the application we are updating) before the installation can continue because i will try to make modifications to these locked files in OnAppInstall

Do we need to entertain the thought of ordering these IAppSetup tasks, rather than providing N hooks and people needing to understand when the right time is to do things?

**Comment by peters** [comment]
> But are these files part of the install?

No

> Do we need to entertain the thought of ordering these IAppSetup tasks

No, it should be as simple as possible. Just thought i make the suggestion, but i realize now that it's better to leave things as they are.

**Comment by peters** [comment]
@shiftkey AppSetup is broken again.

# Log

```
WARN | 2013-09-20 10:13:09  +02 | POCOObservableForProperty: Shimmer.WiXUi.Views.WelcomeView is a POCO type and won't send change notifications, WhenAny will only return a single value!
INFO | 2013-09-20 10:13:10  +02 | WixUiBootstrapper: PlanCompleteObs: got status: '0'
WARN | 2013-09-20 10:13:10  +02 | POCOObservableForProperty: Shimmer.WiXUi.Views.InstallingView is a POCO type and won't send change notifications, WhenAny will only return a single value!
WARN | 2013-09-20 10:13:12  +02 | UpdateManager: Failed to load local release list: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\peters\AppData\Local\autokollekt\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.FileInfo.OpenRead()
   at System.IO.Abstractions.FileInfoWrapper.OpenRead()
   at Shimmer.Client.UpdateManager.checkForUpdate(Boolean ignoreDeltaUpdates, IObserver`1 progress)
INFO | 2013-09-20 10:13:12  +02 | UpdateManager: Reading RELEASES file from C:\Users\peters\AppData\Local\Temp\{7e2bcbfd-f242-48ef-9f40-4305154957f5}\.ba1
WARN | 2013-09-20 10:13:12  +02 | UpdateManager: First run or local directory is corrupt, starting from scratch
INFO | 2013-09-20 10:13:12  +02 | InstallManager: The checking of releases completed - and there was much rejoicing
INFO | 2013-09-20 10:13:12  +02 | InstallManager: HEY! We should be applying update autokollekt-0.1.0-full.nupkg
INFO | 2013-09-20 10:13:12  +02 | InstallManager: The downloading of releases completed - and there was much rejoicing
INFO | 2013-09-20 10:13:12  +02 | UpdateManager: cleanDeadVersions: for version 
INFO | 2013-09-20 10:13:12  +02 | UpdateManager: Writing files to app directory: C:\Users\peters\AppData\Local\autokollekt\app-0.1.0
DEBUG | 2013-09-20 10:13:15  +02 | UpdateManager: AppDomain ID: 2
INFO | 2013-09-20 10:13:15  +02 | UpdateManager: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
INFO | 2013-09-20 10:13:15  +02 | UpdateManager: Processing shortcut 'C:\Program Files (x86)\Red Gate\.NET Reflector\Desktop 7.6\Reflector.exe'
INFO | 2013-09-20 10:13:15  +02 | UpdateManager: Processing shortcut 'C:\Program Files\Adobe\Adobe Photoshop CS6 (64 Bit)\Photoshop.exe'
INFO | 2013-09-20 10:13:15  +02 | UpdateManager: Processing shortcut 'C:\Program Files (x86)\Canon\MP Navigator EX 4.0\mpnex40.exe'
INFO | 2013-09-20 10:13:15  +02 | UpdateManager: Processing shortcut 'C:\Program Files (x86)\ConEmu\ConEmu.exe'
INFO | 2013-09-20 10:13:15  +02 | UpdateManager: Processing shortcut 'C:\Users\peters\Downloads\depends22_x64\depends.exe'
INFO | 2013-09-20 10:13:15  +02 | UpdateManager: Processing shortcut 'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'
INFO | 2013-09-20 10:13:15  +02 | UpdateManager: Processing shortcut 'C:\Users\peters\Documents\software\ilspy\ILSpy.exe'
INFO | 2013-09-20 10:13:15  +02 | UpdateManager: Processing shortcut 'C:\Program Files (x86)\Mozilla Firefox\firefox.exe'
INFO | 2013-09-20 10:13:15  +02 | UpdateManager: Processing shortcut 'C:\Program Files (x86)\PuTTY\putty.exe'
INFO | 2013-09-20 10:13:15  +02 | UpdateManager: Processing shortcut 'C:\Windows\Installer\{31826A0F-5A8D-4276-B41A-5D129BA4EC7F}\ProductIcon.ico'
INFO | 2013-09-20 10:13:15  +02 | UpdateManager: Processing shortcut 'C:\Users\peters\AppData\Roaming\Spotify\spotify.exe'
INFO | 2013-09-20 10:13:15  +02 | UpdateManager: Processing shortcut 'C:\Program Files\Sublime Text 3\sublime_text.exe'
INFO | 2013-09-20 10:13:15  +02 | UpdateManager: Processing shortcut 'C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\devenv.exe'
INFO | 2013-09-20 10:13:15  +02 | UpdateManager: Processing shortcut 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe'
INFO | 2013-09-20 10:13:15  +02 | UpdateManager: Processing shortcut 'C:\Windows\explorer.exe'
INFO | 2013-09-20 10:13:15  +02 | UpdateManager: runPostInstallAndCleanup: finished fixPinnedExecutables
WARN | 2013-09-20 10:13:15  +02 | InstallerHookOperations: Couldn't load types from module C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\autokollekt.exe: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Shimmer.Client.InstallerHookOperations.<findAppSetupsToRun>b__14(Module x)
WARN | 2013-09-20 10:13:15  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-20 10:13:15  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-20 10:13:15  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-20 10:13:15  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-20 10:13:15  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-20 10:13:15  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-20 10:13:15  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-20 10:13:15  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-20 10:13:15  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-20 10:13:15  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-20 10:13:15  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-20 10:13:15  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-20 10:13:15  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-20 10:13:15  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-20 10:13:15  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-20 10:13:15  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-20 10:13:15  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-20 10:13:15  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-20 10:13:15  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'payment.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-20 10:13:15  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'CefSharp, Version=1.25.4.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138' or one of its dependencies. The system cannot find the file specified.
File name: 'CefSharp, Version=1.25.4.0, Culture=neutral, PublicKeyToken=40c4b6fc221f4138'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-20 10:13:15  +02 | InstallerHookOperations: Could not find any AppSetup instances
INFO | 2013-09-20 10:13:15  +02 | InstallerHookOperations: We have an exe: C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\autokollekt.exe
INFO | 2013-09-20 10:13:15  +02 | InstallerHookOperations: installAppVersion: Doing first install for C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\autokollekt.exe
INFO | 2013-09-20 10:13:15  +02 | InstallerHookOperations: installAppVersion: Doing install for version 0.1.0 C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\autokollekt.exe
INFO | 2013-09-20 10:13:15  +02 | InstallerHookOperations: installAppVersion: we have a shortcut C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\autokollekt.exe
INFO | 2013-09-20 10:13:15  +02 | InstallerHookOperations: installAppVersion: we have a shortcut C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\autokollekt.exe
INFO | 2013-09-20 10:13:15  +02 | InstallerHookOperations: installAppVersion: checking shortcut C:\Users\peters\Desktop\AutoKollekt.lnk
INFO | 2013-09-20 10:13:15  +02 | InstallerHookOperations: installAppVersion: checking shortcut C:\Users\peters\AppData\Roaming\Microsoft\Windows\Start Menu\autokollekt\AutoKollekt.lnk
INFO | 2013-09-20 10:13:15  +02 | InstallManager: The applying of releases completed - and there was much rejoicing
INFO | 2013-09-20 10:13:16  +02 | WixUiBootstrapper: ApplyCompleteObs: got restart: 'None', result: 'None', status: '0'
```

**Comment by peters** [comment]
For this particular application all resources/dynamic libraries are repacked into a single executable with the exception of a few native dependencies. One of these are not being properly extracted causing https://github.com/github/Shimmer/blob/master/src/Shimmer.Client/InstallerHookOperations.cs#L172 to fail

**Comment by peters** [comment]
@shiftkey You got mail.

**Comment by shiftkey** [comment]
@peters I'm going to look at the AppSetup things next week (including testing the "load assembly from another location" scenario" mentioned here), but I think the documentation and testing will end up reflecting the "separate assembly for app setup components" thinking we've discussed here.

Is that cool?

**Comment by peters** [comment]
:+1:
