### ISSUE TITLE
Log LoaderException details so we can see what's going on

### ISSUE THREAD

**Issue by shiftkey** [Squirrel/OldSquirrelForWindows#128]
Here: `InstallerHookOperations.<findAppSetupsToRun>`

**Comment by shiftkey** [comment]
Boom d9b1985b5e7e94db32943ff4f8faff77ac473d58

**Comment by peters** [comment]
@shiftkey 0.6.21 %APPDATA%\Shimmer

It's probably failing because autokollekt.infrastructure.dll is missing it's dependencies because of https://github.com/github/Shimmer/issues/125

```
WARN | 2013-09-11 04:04:10  +02 | UpdateManager: Failed to load local release list: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\peters\AppData\Local\autokollekt\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.FileInfo.OpenRead()
   at System.IO.Abstractions.FileInfoWrapper.OpenRead()
   at Shimmer.Client.UpdateManager.checkForUpdate(Boolean ignoreDeltaUpdates, IObserver`1 progress)
INFO | 2013-09-11 04:04:10  +02 | UpdateManager: Reading RELEASES file from C:\Users\peters\AppData\Local\Temp\{40d9d9ce-b3bc-4bb8-bb19-3faf018e4c03}\.ba1
WARN | 2013-09-11 04:04:10  +02 | UpdateManager: First run or local directory is corrupt, starting from scratch
INFO | 2013-09-11 04:04:10  +02 | InstallManager: The checking of releases completed - and there was much rejoicing
INFO | 2013-09-11 04:04:10  +02 | InstallManager: HEY! We should be applying update autokollekt-0.1.0-beta-full.nupkg
INFO | 2013-09-11 04:04:10  +02 | InstallManager: The downloading of releases completed - and there was much rejoicing
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\Common.Logging.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\MarkdownSharp.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\NHttp.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\NLog.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Data.SQLite.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Data.SQLite.Linq.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\NLog.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\ServiceStack.Common.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\ServiceStack.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\ServiceStack.Interfaces.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\ServiceStack.OrmLite.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\ServiceStack.OrmLite.SqliteNET.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\ServiceStack.Redis.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\ServiceStack.ServiceInterface.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\ServiceStack.Text.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.IO.Abstractions.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\HigLabo.Data.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\HigLabo.Mail.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\HigLabo.Net.BoxNet.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\HigLabo.Net.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\HigLabo.Net.Dropbox.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\HigLabo.Net.Facebook.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\HigLabo.Net.Ftp.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\HigLabo.Net.Rss.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\HigLabo.Net.SugarSync.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\HigLabo.Net.Twitter.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\HigLabo.Net.WindowsLive.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\HigLabo.WindowsAzure.RestService.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\Ionic.Zip.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\Microsoft.Threading.Tasks.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\Microsoft.Threading.Tasks.Extensions.Desktop.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\Microsoft.Threading.Tasks.Extensions.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\Microsoft.Web.XmlTransform.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\Newtonsoft.Json.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\NLog.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\Semver.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\ServiceStack.OrmLite.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\ServiceStack.OrmLite.SqliteNET.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\Shimmer.Client.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\Shimmer.Core.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\Sprache.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Data.SQLite.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Data.SQLite.Linq.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.IO.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Reactive.Core.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Reactive.Interfaces.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Reactive.Linq.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Reactive.PlatformServices.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Runtime.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Threading.Tasks.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\NuGet.Core.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\autokollekt.exe to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\Microsoft.Threading.Tasks.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\Microsoft.Threading.Tasks.Extensions.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\NLog.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Data.SQLite.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Data.SQLite.Linq.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Reactive.Core.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Reactive.Interfaces.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Reactive.Linq.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Reactive.PlatformServices.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\nunit.framework.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.IO.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Runtime.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Threading.Tasks.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\Microsoft.Threading.Tasks.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\Microsoft.Threading.Tasks.Extensions.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.IO.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Runtime.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Threading.Tasks.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.IO.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Runtime.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Threading.Tasks.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.IO.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Runtime.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Threading.Tasks.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.IO.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Runtime.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Threading.Tasks.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.IO.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Runtime.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Threading.Tasks.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\Microsoft.Threading.Tasks.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\Microsoft.Threading.Tasks.Extensions.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\Microsoft.Threading.Tasks.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\Microsoft.Threading.Tasks.Extensions.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Reactive.Core.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Reactive.Interfaces.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\System.Reactive.Linq.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\ServiceStack.OrmLite.dll to app directory
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Writing C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\ServiceStack.OrmLite.SqlServer.dll to app directory
DEBUG | 2013-09-11 04:04:12  +02 | UpdateManager: AppDomain ID: 2
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Processing shortcut 'C:\Program Files\Adobe\Adobe Photoshop CS6 (64 Bit)\Photoshop.exe'
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Processing shortcut 'C:\Program Files (x86)\Canon\MP Navigator EX 4.0\mpnex40.exe'
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Processing shortcut 'C:\Program Files (x86)\ConEmu\ConEmu.exe'
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Processing shortcut 'C:\Users\peters\Documents\software\confusor\Confuser.exe'
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Processing shortcut 'C:\Users\peters\Downloads\depends22_x64\depends.exe'
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Processing shortcut 'C:\Program Files (x86)\Google\Chrome\Application\chrome.exe'
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Processing shortcut 'C:\Users\peters\Documents\software\ilspy\ILSpy.exe'
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Processing shortcut 'C:\Program Files (x86)\Mozilla Firefox\firefox.exe'
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Processing shortcut 'C:\Program Files (x86)\Opera Next\launcher.exe'
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Processing shortcut 'C:\Program Files (x86)\PuTTY\putty.exe'
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Processing shortcut 'C:\Users\peters\AppData\Roaming\Spotify\spotify.exe'
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Processing shortcut 'C:\Program Files\Sublime Text 3\sublime_text.exe'
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Processing shortcut 'C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\devenv.exe'
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Processing shortcut 'C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\devenv.exe'
INFO | 2013-09-11 04:04:12  +02 | UpdateManager: Processing shortcut 'C:\Windows\explorer.exe'
WARN | 2013-09-11 04:04:12  +02 | InstallerHookOperations: Couldn't load types from module C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\autokollekt.exe: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Shimmer.Client.InstallerHookOperations.<findAppSetupsToRun>b__13(Module x)
WARN | 2013-09-11 04:04:12  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'autokollekt.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'autokollekt.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-11 04:04:12  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'autokollekt.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'autokollekt.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-11 04:04:12  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'autokollekt.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'autokollekt.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-11 04:04:12  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'autokollekt.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'autokollekt.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-11 04:04:12  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'autokollekt.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'autokollekt.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-11 04:04:12  +02 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'autokollekt.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'autokollekt.infrastructure, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

WARN | 2013-09-11 04:04:12  +02 | InstallerHookOperations: Could not find any AppSetup instances
INFO | 2013-09-11 04:04:12  +02 | InstallerHookOperations: We have an exe: C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\autokollekt.exe
INFO | 2013-09-11 04:04:12  +02 | InstallerHookOperations: installAppVersion: Doing first install for C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\autokollekt.exe
INFO | 2013-09-11 04:04:12  +02 | InstallerHookOperations: installAppVersion: Doing install for version 0.1.0 C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\autokollekt.exe
INFO | 2013-09-11 04:04:12  +02 | InstallerHookOperations: installAppVersion: we have a shortcut C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\autokollekt.exe
INFO | 2013-09-11 04:04:12  +02 | InstallerHookOperations: installAppVersion: we have a shortcut C:\Users\peters\AppData\Local\autokollekt\app-0.1.0\autokollekt.exe
INFO | 2013-09-11 04:04:12  +02 | InstallerHookOperations: installAppVersion: checking shortcut C:\Users\peters\Desktop\AutoKollekt.lnk
INFO | 2013-09-11 04:04:12  +02 | InstallerHookOperations: installAppVersion: deleting existing file
INFO | 2013-09-11 04:04:12  +02 | InstallerHookOperations: installAppVersion: checking shortcut C:\Users\peters\AppData\Roaming\Microsoft\Windows\Start Menu\autokollekt\AutoKollekt.lnk
INFO | 2013-09-11 04:04:12  +02 | InstallManager: The applying of releases completed - and there was much rejoicing
```

**Comment by shiftkey** [comment]
@peters if you can give me feedback on #125 (it was fairly straightforward to implement) let's push out another release and confirm you're back on track

**Comment by shiftkey** [comment]
EDIT: #131 is the fix for it
