### ISSUE TITLE
Crash when running 'New-Release'

### ISSUE THREAD

**Issue by peters** [Squirrel/OldSquirrelForWindows#179]
Building two consecutive releases causes Shimmer to crash.

Pretty much:

``` ps
PM> New-Release
PM> New-Release
```

:boom: :boom: :boom: :boom: 

``` ps
PM> New-Release
Shimmer: Building project opus
Shimmer: Publishing release for project opus
Shimmer: Checking C:\Users\peters\Documents\GitHub2\opus\src\opus\bin\x86\Release\ for packages

Shimmer: Found package C:\Users\peters\Documents\GitHub2\opus\src\opus\bin\x86\Release\opus.0.1.0.nupkg

Shimmer: Publishing artifacts to C:\Users\peters\Documents\GitHub2\opus\Releases

Shimmer: Using packages directory C:\Users\peters\Documents\GitHub2\opus\packages

Shimmer: Full release: C:\Users\peters\Documents\GitHub2\opus\Releases\opus-0.1.0-full.nupkg

Shimmer: Creating installer for C:\Users\peters\Documents\GitHub2\opus\Releases\opus-0.1.0-full.nupkg
Shimmer: Running candle.exe
Windows Installer Xml Compiler version 3.7.1224.0
Copyright (C) Outercurve Foundation. All rights reserved.

template.wxs
Shimmer: Running light.exe
Windows Installer Xml Linker version 3.7.1224.0
Copyright (C) Outercurve Foundation. All rights reserved.

PM> New-Release
Shimmer: Building project opus
Shimmer: Publishing release for project opus
Shimmer: Checking C:\Users\peters\Documents\GitHub2\opus\src\opus\bin\x86\Release\ for packages

Shimmer: Found package C:\Users\peters\Documents\GitHub2\opus\src\opus\bin\x86\Release\opus.0.1.0.nupkg

Shimmer: Publishing artifacts to C:\Users\peters\Documents\GitHub2\opus\Releases

Shimmer: Using packages directory C:\Users\peters\Documents\GitHub2\opus\packages
CreateReleasePackage.exe : 
At C:\Users\peters\Documents\GitHub2\opus\packages\Shimmer.0.7.0\tools\commands.psm1:70 char:26
+         $releaseOutput = & $createReleasePackageExe -o $ReleasesDir -p $packageD ...
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Unhandled Exception: 
System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Ionic.Zip.ZipFile.Save()
   at Shimmer.Core.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor)
   at CreateReleasePackage.Program.Main(String[] args)


You cannot call a method on a null-valued expression.
At C:\Users\peters\Documents\GitHub2\opus\packages\Shimmer.0.7.0\tools\commands.psm1:72 char:9
+         $packages = $releaseOutput.Split(";")
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Cannot index into a null array.
At C:\Users\peters\Documents\GitHub2\opus\packages\Shimmer.0.7.0\tools\commands.psm1:73 char:9
+         $fullRelease = $packages[0].Trim()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray


Shimmer: Full release: 

Shimmer: Creating installer for 
Shimmer: Running candle.exe
Windows Installer Xml Compiler version 3.7.1224.0
Copyright (C) Outercurve Foundation. All rights reserved.

template.wxs
C:\Users\peters\Documents\GitHub2\opus\src\opus\bin\x86\Release\template.wxs(34) : error CNDL0006 : The Payload/@SourceFile attribute's value cannot be an empty string.  If you want the value to be null or empty, si
mply remove the entire attribute.
Shimmer: Running light.exe
light.exe : error LGHT0103 : The system cannot find the file 'C:\Users\peters\Documents\GitHub2\opus\src\opus\bin\x86\Release\\template.wixobj' with type 'Source'.
PM> 
```

**Comment by peters** [comment]
Clearing the content of `Releases` directory before creating a new Release does the trick :+1:

**Comment by shiftkey** [comment]
```
Unhandled Exception: 
System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at Ionic.Zip.ZipFile.Save()
   at Shimmer.Core.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor)
   at CreateReleasePackage.Program.Main(String[] args)
```

I'm curious if this is repeatable. Feel free to reopen it if you can isolate where the script needs to be more robust.
