### ISSUE TITLE
Crash when using <references />

### ISSUE THREAD

**Issue by peters** [Squirrel/OldSquirrelForWindows#180]
If you specify a third party reference (which is not referenced by the main project, but is a build dependency) things go to shit:
# Nuspec

``` xml
<references>
  <reference file="some.referenced.project.dll" />
</references>
```
# Error

``` ps
PM> New-Release
Shimmer: Building project opus
Shimmer: Publishing release for project opus
Shimmer: Checking C:\Users\peters\Documents\GitHub2\opus\src\opus\bin\x86\Release\ for packages

Shimmer: Found package C:\Users\peters\Documents\GitHub2\opus\src\opus\bin\x86\Release\opus.0.1.0.nupkg

Shimmer: Publishing artifacts to C:\Users\peters\Documents\GitHub2\opus\Releases

Shimmer: Using packages directory C:\Users\peters\Documents\GitHub2\opus\packages
CreateReleasePackage.exe : 
At C:\Users\peters\Documents\GitHub2\opus\packages\Shimmer.0.7.0\tools\commands.psm1:70 char:26
+         $releaseOutput = & $createReleasePackageExe -o $ReleasesDir -p $packageD ...
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Unhandled Exception: 
System.IO.FileFormatException: Archive file cannot be size 0.
   at MS.Internal.IO.Zip.ZipArchive.OpenOnStream(Stream stream, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at NuGet.ZipPackage.EnsureManifest()
   at Shimmer.Core.ReleasePackage.get_SuggestedReleaseFileName()
   at CreateReleasePackage.Program.Main(String[] args)


You cannot call a method on a null-valued expression.
At C:\Users\peters\Documents\GitHub2\opus\packages\Shimmer.0.7.0\tools\commands.psm1:72 char:9
+         $packages = $releaseOutput.Split(";")
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

Cannot index into a null array.
At C:\Users\peters\Documents\GitHub2\opus\packages\Shimmer.0.7.0\tools\commands.psm1:73 char:9
+         $fullRelease = $packages[0].Trim()
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray


Shimmer: Full release: 

Shimmer: Creating installer for 
CreateReleasePackage.exe : 
At C:\Users\peters\Documents\GitHub2\opus\packages\Shimmer.0.7.0\tools\commands.psm1:19 char:19
+     $resultFile = & $createReleasePackageExe --preprocess-template $templateFile ...
+                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Unhandled Exception: 
System.IO.FileFormatException: Archive file cannot be size 0.
   at MS.Internal.IO.Zip.ZipArchive.OpenOnStream(Stream stream, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.ZipPackage..ctor(Stream s, FileMode mode, FileAccess access, Boolean streaming)
   at System.IO.Packaging.Package.Open(Stream stream, FileMode packageMode, FileAccess packageAccess, Boolean streaming)
   at NuGet.ZipPackage.EnsureManifest()
   at CreateReleasePackage.ParseCommands.processTemplateFile(String packageFile, String templateFile)
   at CreateReleasePackage.ParseCommands.ParseOptions(String[] args)
   at CreateReleasePackage.Program.Main(String[] args)


Move-Item : Cannot bind argument to parameter 'Path' because it is null.
At C:\Users\peters\Documents\GitHub2\opus\packages\Shimmer.0.7.0\tools\commands.psm1:107 char:8
+     mv $candleTemplate $wixTemplate | Out-Null
+        ~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Move-Item], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.MoveItemCommand

Get-Content : Cannot find path 'C:\Users\peters\Documents\GitHub2\opus\src\opus\bin\x86\Release\template.wxs' because it does not exist.
At C:\Users\peters\Documents\GitHub2\opus\packages\Shimmer.0.7.0\tools\commands.psm1:111 char:21
+     $templateText = Get-Content $wixTemplate
+                     ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\peters...se\template.wxs:String) [Get-Content], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetContentCommand

Shimmer: Running candle.exe
Windows Installer Xml Compiler version 3.7.1224.0
Copyright (C) Outercurve Foundation. All rights reserved.

template.wxs
C:\Users\peters\Documents\GitHub2\opus\src\opus\bin\x86\Release\template.wxs : error CNDL0104 : Not a valid source file; detail: Root element is missing.
Shimmer: Running light.exe
light.exe : error LGHT0103 : The system cannot find the file 'C:\Users\peters\Documents\GitHub2\opus\src\opus\bin\x86\Release\\template.wixobj' with type 'Source'.
PM> 
```

**Comment by shiftkey** [comment]
I don't have a specific warning for this (haven't been able to create a package with a bad reference due to getting this build warning):

> C:\Users\brendanforster\Documents\GitHub\Shimmer.Samples\src\desktop.nuget\NuGet.targets(101,9): 
> error : Invalid assembly reference 'lolololol.dll'. Ensure that a file named 'lolololol.dll' exists in the lib directory.

But as part of #184 I'm catching and bailing out on the error.

Can you put together a small repro of a project which can be build successfully but has a bad reference value?

**Comment by peters** [comment]
@shiftkey :+1: :+1: 0.7.1
![image](https://f.cloud.github.com/assets/869/1233919/eff8eb90-294b-11e3-8daa-6a4f61ffe6fb.png)

**Comment by peters** [comment]
Ahh i totally forgot about this, i'll try to get a reproduce project going soon and get back to you ;)

**Comment by shiftkey** [comment]
Feel free to reopen this when you do
