### ISSUE TITLE
Broken installer

### ISSUE THREAD

**Issue by peters** [Squirrel/OldSquirrelForWindows#181]
# Reproduce steps

1) Install
2) Uninstall
3) Install
4) :boom: 

Deleting `%LocalAppData%\MyFancyAppName` before attempting 3) resolves the problem.
# Log

```
[WARN][2013-09-25T10:52:54] POCOObservableForProperty: Shimmer.WiXUi.Views.WelcomeView is a POCO type and won't send change notifications, WhenAny will only return a single value!
[INFO][2013-09-25T10:52:55] WixUiBootstrapper: PlanCompleteObs: got status: '0'
[WARN][2013-09-25T10:52:55] POCOObservableForProperty: Shimmer.WiXUi.Views.InstallingView is a POCO type and won't send change notifications, WhenAny will only return a single value!
[INFO][2013-09-25T10:52:56] UpdateManager: Reading RELEASES file from C:\Users\peters\AppData\Local\Temp\{870be659-373d-4699-8b48-e433df19bccd}\.ba1
[INFO][2013-09-25T10:52:56] UpdateManager: No updates, remote and local are the same
[INFO][2013-09-25T10:52:56] InstallManager: The checking of releases completed - and there was much rejoicing
[WARN][2013-09-25T10:52:56] InstallManager: executeInstall: the directory {0} doesn't exist - cannot find the current app?!!?
[WARN][2013-09-25T10:52:56] InstallManager: Updating using deltas has failed: System.InvalidOperationException: AwaitableAsyncSubject<T>.GetResult() completed without having a result. That's bad.
   at ReactiveUIMicro.AwaitableAsyncSubject`1.GetResult()
   at Shimmer.Client.InstallManager.<executeInstall>d__9.MoveNext()
[INFO][2013-09-25T10:52:57] UpdateManager: Reading RELEASES file from C:\Users\peters\AppData\Local\Temp\{870be659-373d-4699-8b48-e433df19bccd}\.ba1
[INFO][2013-09-25T10:52:57] UpdateManager: No updates, remote and local are the same
[INFO][2013-09-25T10:52:57] InstallManager: The checking of releases completed - and there was much rejoicing
[WARN][2013-09-25T10:52:57] InstallManager: executeInstall: the directory {0} doesn't exist - cannot find the current app?!!?
[ERROR][2013-09-25T10:52:57] WixUiBootstrapper: Something unexpected happened: System.InvalidOperationException: AwaitableAsyncSubject<T>.GetResult() completed without having a result. That's bad.
   at ReactiveUIMicro.AwaitableAsyncSubject`1.GetResult()
   at Shimmer.Client.InstallManager.<executeInstall>d__9.MoveNext()
[WARN][2013-09-25T10:52:57] POCOObservableForProperty: Shimmer.WiXUi.Views.ErrorView is a POCO type and won't send change notifications, WhenAny will only return a single value!
```

**Comment by shiftkey** [comment]
Which version? 

The latest bits have fixed the issue where `AwaitableAsyncSubject<T>` give a more useful stacktrace, so if it's repeatable with that I'd love to see those stacktraces...

**Comment by peters** [comment]
@shiftkey  0.7.0

Hmm, if you want to reproduce this, you need to create a broken installer. Try throwing an exception in AppSetup so that the installer fails.

**Comment by peters** [comment]
@shiftkey Also, got `AppSetup` issues again. Program installs fine though ;)

```
[WARN][2013-09-26T09:42:01] POCOObservableForProperty: Shimmer.WiXUi.Views.WelcomeView is a POCO type and won't send change notifications, WhenAny will only return a single value!
[INFO][2013-09-26T09:42:02] WixUiBootstrapper: PlanCompleteObs: got status: '0'
[WARN][2013-09-26T09:42:02] POCOObservableForProperty: Shimmer.WiXUi.Views.InstallingView is a POCO type and won't send change notifications, WhenAny will only return a single value!
[WARN][2013-09-26T09:42:03] UpdateManager: Failed to load local release list: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\peters\AppData\Local\opus\packages\RELEASES'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.FileInfo.OpenRead()
   at System.IO.Abstractions.FileInfoWrapper.OpenRead()
   at Shimmer.Client.UpdateManager.checkForUpdate(Boolean ignoreDeltaUpdates, IObserver`1 progress)
[INFO][2013-09-26T09:42:03] UpdateManager: Reading RELEASES file from C:\Users\peters\AppData\Local\Temp\{5a834b71-e7d0-4921-968c-00d5d70b6856}\.ba1
[WARN][2013-09-26T09:42:03] UpdateManager: First run or local directory is corrupt, starting from scratch
[INFO][2013-09-26T09:42:03] InstallManager: The checking of releases completed - and there was much rejoicing
[INFO][2013-09-26T09:42:03] InstallManager: HEY! We should be applying update opus-0.1.0-full.nupkg
[INFO][2013-09-26T09:42:03] InstallManager: The downloading of releases completed - and there was much rejoicing
[INFO][2013-09-26T09:42:03] UpdateManager: cleanDeadVersions: for version 
[INFO][2013-09-26T09:42:03] UpdateManager: Writing files to app directory: C:\Users\peters\AppData\Local\opus\app-0.1.0
[DEBUG][2013-09-26T09:42:06] UpdateManager: AppDomain ID: 2
[INFO][2013-09-26T09:42:06] UpdateManager: fixPinnedExecutables: oldAppDirectories is empty, this is pointless
[INFO][2013-09-26T09:42:06] UpdateManager: runPostInstallAndCleanup: finished fixPinnedExecutables
[WARN][2013-09-26T09:42:06] InstallerHookOperations: Couldn't load types from module C:\Users\peters\AppData\Local\opus\app-0.1.0\opus.exe: System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Shimmer.Client.InstallerHookOperations.<findAppSetupsToRun>b__14(Module x)
[WARN][2013-09-26T09:42:06] InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'MetroFramework, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'MetroFramework, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null'

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

[WARN][2013-09-26T09:42:06] InstallerHookOperations: Could not find any AppSetup instances
[INFO][2013-09-26T09:42:06] InstallerHookOperations: We have an exe: C:\Users\peters\AppData\Local\opus\app-0.1.0\opus.exe
[INFO][2013-09-26T09:42:06] InstallerHookOperations: installAppVersion: Doing first install for C:\Users\peters\AppData\Local\opus\app-0.1.0\opus.exe
[INFO][2013-09-26T09:42:06] InstallerHookOperations: installAppVersion: Doing install for version 0.1.0 C:\Users\peters\AppData\Local\opus\app-0.1.0\opus.exe
[INFO][2013-09-26T09:42:06] InstallerHookOperations: installAppVersion: we have a shortcut C:\Users\peters\AppData\Local\opus\app-0.1.0\opus.exe
[INFO][2013-09-26T09:42:06] InstallerHookOperations: installAppVersion: we have a shortcut C:\Users\peters\AppData\Local\opus\app-0.1.0\opus.exe
[INFO][2013-09-26T09:42:06] InstallerHookOperations: installAppVersion: checking shortcut C:\Users\peters\Desktop\Opus.lnk
[INFO][2013-09-26T09:42:06] InstallerHookOperations: installAppVersion: checking shortcut C:\Users\peters\AppData\Roaming\Microsoft\Windows\Start Menu\opus\Opus.lnk
[INFO][2013-09-26T09:42:06] InstallManager: The applying of releases completed - and there was much rejoicing
[INFO][2013-09-26T09:42:06] WixUiBootstrapper: ApplyCompleteObs: got restart: 'None', result: 'None', status: '0'

```

**Comment by shiftkey** [comment]
I'm curious if the application was open when you were uninstalling:

> 1) Install
> 2) Uninstall
> 3) Install
> 4) :boom:
> 
> Deleting %LocalAppData%\MyFancyAppName before attempting 3) resolves the problem.

Because if you try and uninstall the application while it's running, we'll mark the files as `MOVEFILE_DELAY_UNTIL_REBOOT`. That might cause an issue when you try and install it again after.

**Comment by shiftkey** [comment]
> Also, got AppSetup issues again. Program installs fine though ;)

Haven't forgotten, it's still on the list

**Comment by peters** [comment]
@shiftkey Finally i was able reproduce this sucker without breaking the installer. If you have `%LocalAppData%\App` open in Windows Explorer and then uninstall. But if you try to run Setup.exe after uninstall it breaks (works as expected if you delete the folder before you attempt to reinstall).
