### ISSUE TITLE
New-Release doesn't find project dependencies

### ISSUE THREAD

**Issue by flagbug** [Squirrel/OldSquirrelForWindows#227]
I have a solution with multiple projects, each with a .nuspec file and `BuildPackage` enabled. The main project has a dependency on the other two projects and I specified them as dependency in the .nuspec of the main project as described [here](https://github.com/squirrel/Squirrel.Windows/wiki/Specifying-The-Right-Dependencies#project-references)

When creating a `New-Release`, I get the following error:

```
CreateReleasePackage.exe : 
At C:\Users\Dennis\Dropbox\Projects\Espera\Espera\packages\Shimmer.0.7.4\tools\commands.psm1:70 char:26
+         $releaseOutput = & $createReleasePackageExe -o $ReleasesDir -p $packageD ...
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError

Unexpected exception occurred creating package:

System.Exception: Couldn't find file for package in C:\Users\Dennis\Dropbox\Projects\Espera\Espera\packages: Espera.Core
   at Shimmer.Core.ReleasePackage.<>c__DisplayClass1c.<findAllDependentPackages>b__19(PackageDependency dependency)
   at System.Linq
.Enumerable.<SelectManyIterator>d__14`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Shimmer.Core.ReleasePackage.findAllDependentPackages(IPackage package, String packagesRootDir, HashSet`1 packageCache, FrameworkName frameworkName)
   at Shimmer.Core.ReleasePackage.CreateReleasePackage(String outputFile, String packagesRootDir, Func`2 releaseNotesProcessor)
   at CreateReleasePackage.Program.Main(String[] args)
```

Seems like `CreateReleasePackage.exe`  looks for the project dependencies in the `packages` directory, but the built .nupgk files are still in their build output folders

**Comment by ses4j** [comment]
Did you ever resolve this?

**Comment by flagbug** [comment]
@ses4j Nope, that's just not possible at the moment

**Comment by ses4j** [comment]
So what can you do to get the project dependencies outputs in the right place?

**Comment by dchaib** [comment]
Does this mean it is not yet possible to use Squirrel with a solution that has more than one project? Even though it is fully documented?

**Comment by flagbug** [comment]
It is possible if you manually copy the resulting .nupkg files of the projects into the releases folder

**Comment by dchaib** [comment]
I must have done something wrong then, because I tried what you said and I still have the same error as the one you mentioned at the beginning.

**Comment by dchaib** [comment]
I have tried to put ExternalProject-0.5.0-beta-full.nupkg in
- the `Releases` folder
- the `packages` folder
- a new `packages\ExternalProject` folder

It never worked...

**Comment by flagbug** [comment]
Ah yes, I meant The packages folder...don't  understand why it doesn't work for you though

**Comment by flagbug** [comment]
Try to delete the '-full' from the filename

**Comment by dchaib** [comment]
I just managed to make it work by removing "-full" and also changing "-" into ".". In conclusion, I use this file:
`packages\ExternalProject\ExternalProject.0.5.0-beta.nupkg`
instead of:
`packages\ExternalProject\ExternalProject-0.5.0-beta-full.nupkg`.
Thanks for your help!
