### ISSUE TITLE
"Deleted" folders interfere with upgrades

### ISSUE THREAD

**Issue by shiftkey** [Squirrel/OldSquirrelForWindows#74]
So after doing an upgrade I have these two folders:

![screen shot 2013-09-01 at 11 17 49 pm](https://f.cloud.github.com/assets/359239/1064055/0ad3acec-1309-11e3-8b78-288ba0fc6f31.png)

They're both marked "delete at next reboot" and subsequently don't have an owner:

![screen shot 2013-09-01 at 11 19 22 pm](https://f.cloud.github.com/assets/359239/1064056/2c47e01e-1309-11e3-97a8-7956a31b6abe.png)

What's annoying about this is that I can't install a new version _until the next reboot_ because it tries to delete these directories - and it throws a hissy fit when it can't.

```
WARN | 2013-09-01 10:58:00 PM +10 | UpdateManager: Couldn't delete old app directory on next reboot: 
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at Shimmer.Core.Utility.safeDeleteFileAtNextDir(String name)
   at Shimmer.Core.Utility.<DeleteDirectoryAtNextReboot>b__1c(FileInfo x)
   at System.Linq.EnumerableExtensions.ForEach[TSource](IEnumerable`1 source, Action`1 onNext)
   at Shimmer.Core.Utility.DeleteDirectoryAtNextReboot(String directoryPath)
   at Shimmer.Client.UpdateManager.<cleanUpOldVersions>b__51(DirectoryInfoBase oldAppRoot)

...

WARN | 2013-09-01 11:10:05 PM +10 | InstallManager: Updating using deltas has failed: 
System.UnauthorizedAccessException: Access to the path 
'C:\Users\brendanforster\AppData\Local\TestApp\app-1.3.0\MarkdownSharp.dll' is denied.
   at ReactiveUIMicro.AwaitableAsyncSubject`1.GetResult()
   at Shimmer.Client.InstallManager.<executeInstall>d__9.MoveNext()

...

WARN | 2013-09-01 11:10:10 PM +10 | UpdateManager: : System.UnauthorizedAccessException: 
Access to the path 'C:\Users\brendanforster\AppData\Local\TestApp\app-1.1.0' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path)
   at Shimmer.Core.Utility.DeleteDirectory(String directoryPath)
   at Shimmer.Client.UpdateManager.<>c__DisplayClass6a.<cleanDeadVersions>b__62()
   at System.Reactive.Linq.QueryLanguage.<>c__DisplayClass131.<>c__DisplayClass133.<ToAsync>b__130()
```

I think we need to be more classy with our checks and cleanup of old versions...

**Comment by anaisbetts** [comment]
Wait, why is the _new_ version marked for deletion?

**Comment by shiftkey** [comment]
My latest version is 1.5 (it's not there because I suspect the `cleanDeadVersions` call is failing so it gives up).

These are both old versions. Yes, I'm probably doing naughty things. :trollface:

**Comment by shiftkey** [comment]
Going to re-test this scenario:
- open app version 1.0
- generate  and apply update 1.1
- restart app
- generate and apply update 1.2
- restart app
- close app
- uninstall app

Expected behaviour:
- app can uninstall successfully
- any remaining files are marked as "delete on next boot"
