### ISSUE TITLE
ReflectionTypeLoadException when finding AppSetups

### ISSUE THREAD

**Issue by shiftkey** [Squirrel/OldSquirrelForWindows#75]
Using TestApp (need to isolate a bette repro - this is just a reminder for me):

```
WARN | 2013-09-01 10:58:04 PM +10 | UpdateManager: Couldn't load types from 
module: System.Reflection.ReflectionTypeLoadException: Unable to load one or more
of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at Shimmer.Client.InstallerHookOperations.<findAppSetupsToRun>b__11(Module x)
```

**Comment by shiftkey** [comment]
TODO: 
- better logging around what `LoaderExceptions` are being raised

**Comment by shiftkey** [comment]
Current status:

```
WARN | 2013-09-10 08:44:10 PM -07 | InstallerHookOperations: LoaderException found: System.IO.FileNotFoundException: Could not load file or assembly 'Libronix.Utility.Windows.Controls, Version=9.42.0.1, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'Libronix.Utility.Windows.Controls, Version=9.42.0.1, Culture=neutral, PublicKeyToken=null'

=== Pre-bind state information ===
LOG: User = LRSCORP\allen.petersen
LOG: DisplayName = Libronix.Utility.Windows.Controls, Version=9.42.0.1, Culture=neutral, PublicKeyToken=null
 (Fully-specified)
LOG: Appbase = file:///C:/Users/allen.petersen/AppData/Local/Temp/{11de21d0-7da0-475e-8393-c55577235a9c}/.ba1/
LOG: Initial PrivatePath = NULL
Calling assembly : (Unknown).
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\Users\allen.petersen\AppData\Local\Temp\{11de21d0-7da0-475e-8393-c55577235a9c}\.ba1\BootstrapperCore.config
LOG: Using host configuration file: C:\Users\ALLEN~1.PET\AppData\Local\Temp\{11de21d0-7da0-475e-8393-c55577235a9c}\.ba1\BootstrapperCore.config
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Policy not being applied to reference at this time (private, custom, partial, or location-based assembly bind).
LOG: Attempting download of new URL file:///C:/Users/allen.petersen/AppData/Local/Temp/{11de21d0-7da0-475e-8393-c55577235a9c}/.ba1/Libronix.Utility.Windows.Controls.DLL.
LOG: Attempting download of new URL file:///C:/Users/allen.petersen/AppData/Local/Temp/{11de21d0-7da0-475e-8393-c55577235a9c}/.ba1/Libronix.Utility.Windows.Controls/Libronix.Utility.Windows.Controls.DLL.
LOG: Attempting download of new URL file:///C:/Users/allen.petersen/AppData/Local/Temp/{11de21d0-7da0-475e-8393-c55577235a9c}/.ba1/Libronix.Utility.Windows.Controls.EXE.
LOG: Attempting download of new URL file:///C:/Users/allen.petersen/AppData/Local/Temp/{11de21d0-7da0-475e-8393-c55577235a9c}/.ba1/Libronix.Utility.Windows.Controls/Libronix.Utility.Windows.Controls.EXE.
```
